
title: dgoo 기술 블로그
email: gmrmgmrmal@gmail.com
description: |
  1일 1커밋 가능할까
baseurl: ''
url: 'http://dgoo.github.io'
timezone: Asia/Seoul

repository: dgoo/dgoo.github.io

permalink: /:year/:month/:day/:title

markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: '/page/:num'

collections:
  blogs:
    output: true
    permalink: /blogs/:path
  tags:
    output: true
    permalink: /tags/:path

defaults:
  - scope:
      path: ''
      type: blogs
    values:
      layout: blogs
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

exclude: [README.md, Gemfile, Gemfile.lock]

keep_files: [assets]
github: [metadata]

name: 'dgoo'
author: 'dgoo'
author_image: '/assets/images/author.jpg'
image: '/assets/images/default_cover.jpg'

asset_url: /assets
google_analytics:
  ua: 'UA-125568239-1'
facebook:
  app_id: '2154627707894495'
  username: dgoo
# twitter:
  # username: dgoo
github_url:
  username: dgoo